const files = [
  "Logo01.webp",
  "Logo02.webp",
  "Logos03.webp",
  "Logos04.webp",
  "Logos05.webp",
  "Logos06.webp",
  "Logos07.webp",
  "Logos08.webp",
  "Logos09.webp",
  "Logos10.webp",
  "Logos11.webp",
  "Logos12.webp",
  "Logos13.webp",
  "Logos14.webp",
  "Logos15.webp",
  "Logos16.webp",
  "Logos17.webp",
  "Logos18.webp",
  "Logos19.webp",
  "Logos20.webp",
  "Logos21.webp",
  "Logos22.webp",
  "Logos23.webp",
  "Logos24.webp",
  "Logos25.webp",
];

export const clientLogos: string[] = files.map((f) => `/clients/${f}`);
